### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by shahzebsiddiqui** [E4S-Project/testsuite#2]
@sameershende @wspear @eugeneswalker 

According to E4S documentation it states 

```
Distribution
E4S is open source software published under the MIT License. E4S can be redistributed and modified under the terms of this license. E4S packages each have their own open source license.
```

Please consider adding a LICENSE file, if its MIT for all the projects including E4S Testsuite than you can use the MIT template found here: https://choosealicense.com/licenses/mit/

**Comment by eugeneswalker** [comment]
MIT LICENSE has been added. Thank you!
