### ISSUE TITLE
superlu-dist-nonspacktest fails on JLSE

### ISSUE THREAD

**Issue by koysean** [E4S-Project/testsuite#63]
The superlu-dist-nonspacktest test fails at the compile stage. This issue has the same root cause as https://github.com/E4S-Project/testsuite/issues/62.

The culprit seems to be these lines:
https://github.com/E4S-Project/testsuite/blob/0e7604e7ac2d27f753e504d4b4e83e22b4d3ead2/validation_tests/superlu-dist-nonspacktest/EXAMPLE/compile.sh#L16-L21

**Comment by wspear** [comment]
I've removed this test. The spack internal version should be sufficient.
