### ISSUE TITLE
netcdf-fortran test fails

### ISSUE THREAD

**Issue by koysean** [E4S-Project/testsuite#69]
The netcdf-fortran test has a typo.

The compile line is `$TEST_FTN_MPI simple_xy_wr.f90 -o simple_xy_wr -I${NETCDF_FORTRAN_ROOT}/include -L${NETCDF_FORTRAN_ROOT}/lib -Wl,-rpath,${NETCDF_FORTRAN_ROOT}/lib  -lnetcdff`

emphasis on `-o simple_xy_wr`.

The run line is `$TEST_RUN ./simple_xy_nc4_wr`, so the test always fails since `simple_xy_nc4_wr` doesn't exist.

**Comment by eugeneswalker** [comment]
Thank you for pointing this out!
